application: userapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /media
  static_dir: media
- url: /scripts
  static_dir: scripts
- url: /.* #.* should always be first (order matters)
  script: main.app
- url: /scripts
  static_dir: scripts

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
#- name: oauth2client
#  version: latest
