runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /styles
  static_dir: styles
- url: /media
  static_dir: media
- url: /scripts
  static_dir: scripts
- url: /.* #.* should always be first (order matters)
  script: main.app
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
